# ClimaX Wildfire Segmentation Config
# This config file defines the settings for training a ClimaX model on wildfire segmentation tasks
seed_everything: 42

# Trainer configuration
trainer:
  accelerator: auto
  strategy: ddp
  devices: 5
  num_nodes: 1
  precision: 16
  max_epochs: 100
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  log_every_n_steps: 1
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  default_root_dir: ./outputs/climax-wildfire
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: ./outputs/climax-wildfire
      name: climax_wildfire_segmentation
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val/f1
        mode: max
        save_top_k: 3
        verbose: true
        dirpath: null
        filename: "{epoch:02d}-{val/f1:.4f}"
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val/f1
        patience: 10
        mode: max
        verbose: true
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step

# Data configuration
data:
  class_path: dataloader.FireSpreadDataModule.FireSpreadDataModule
  init_args:
    data_dir: /media/staging1/dhwang/wildfire_ts/wildfirespread
    batch_size: 128
    n_leading_observations: 1
    n_leading_observations_test_adjustment: 1
    crop_side_length: 128
    load_from_hdf5: false
    num_workers: 4
    remove_duplicate_features: true
    predict_active_map_only: true
    features_to_keep: null
    return_doy: false
    data_fold_id: 0

# Model configuration
model:
  class_path: climax_wildfire_segmentation.ClimaXWildfireSegmentationModule
  init_args:
    net:
      class_path: climax_wildfire_segmentation.ClimaXWildfireSegmentation
      init_args:
        default_vars: [
          "M11", "I2", "I1", "NDVI_last", "EVI2_last", "total precipitation",
          "wind speed", "wind direction", "minimum temperature", "maximum temperature",
          "energy release component", "specific humidity", "slope", "aspect",
          "elevation", "pdsi", "LC_Type1", "forecast total precipitation",
          "forecast wind speed", "forecast wind direction", "forecast temperature",
          "forecast specific humidity"
        ]
        img_size: [128, 128]
        patch_size: 8
        embed_dim: 768
        depth: 8
        decoder_depth: 2
        num_heads: 8
        mlp_ratio: 4
        drop_path: 0.1
        drop_rate: 0.1
        parallel_patch_embed: false
    lr: 1e-3
    beta_1: 0.9
    beta_2: 0.95
    weight_decay: 1e-5
    warmup_epochs: 0
    max_epochs: 100

# Move ClimaX parameters under model config since they're now specified there
flatten_temporal_dimension: true

# Run configuration
name: climax_wildfire_segmentation
do_train: true
do_validate: true
do_test: true
do_predict: true
pretrained_weights: null
ckpt_path: null