# Wildfire ClimaX Configuration for Lightning CLI - Adapted for Stream-based Dataset
# NOTE: This config assumes 'datamodule_class=WildfireDataModule' is provided to LightningCLI
seed_everything: 42

# ---------------------------- TRAINER -------------------------------------------
trainer:
  default_root_dir: ${oc.env:OUTPUT_DIR,./wildfire_stream_outputs}
  precision: bf16  # Use 16-bit mixed precision
  accelerator: gpu
  devices: 5
  strategy:
    class_path: pytorch_lightning.strategies.DDPStrategy
    init_args:
      find_unused_parameters: false
      static_graph: true

  gradient_clip_val: 1.0
  enable_progress_bar: true
  sync_batchnorm: true
  enable_checkpointing: true
  resume_from_checkpoint: null
  fast_dev_run: false

  # Step-based training instead of epoch-based
  max_steps: 200000  # Use steps instead of epochs
  max_epochs: null   # Disable epoch-based training
  log_every_n_steps: 50

  logger:
    class_path: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: ${trainer.default_root_dir}/logs
      name: "wildfire_climax_stream"
      version: null
      log_graph: false
      default_hp_metric: true
      prefix: ""

  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"

    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: "${trainer.default_root_dir}/checkpoints"
        monitor: null  # No metric to monitor, save based on steps
        save_top_k: -1  # Save all checkpoints
        every_n_train_steps: 5000  # Save every 500 training steps
        save_last: true
        verbose: false
        filename: "step_{step:06d}"
        auto_insert_metric_name: false

    - class_path: pytorch_lightning.callbacks.RichProgressBar

# ---------------------------- MODEL -------------------------------------------
model:
    lr: 5e-4
    beta_1: 0.9
    beta_2: 0.95
    weight_decay: 1e-5
    # Step-based scheduler parameters 
    warmup_steps: 10000     # Number of warmup steps (replaced warmup_epochs)
    max_steps: 200000      # Total steps for scheduler (replaced max_epochs)
    warmup_start_factor: 0.001
    eta_min: 1e-8
    pretrained_path: ""
    prediction_range: 1

    # Network architecture passed to the model's init
    net:
      class_path: climax.arch.ClimaX
      init_args:
        default_vars: [
          # Align with the NPZ file column names
          "I1", "M4", "M3", "M11", "I2", "I3", "aerosol depth", "NDVI_last", "EVI2_last",
          "total precipitation", "wind speed", "wind direction", "minimum temperature",
          "maximum temperature", "energy release component", "specific humidity",
          "pdsi", "LC_Type1", "forecast total precipitation", "forecast wind speed",
          "forecast wind direction", "forecast temperature", "forecast specific humidity",
          "slope", "aspect", "elevation"
        ]
        img_size: [128, 128]
        patch_size: 8
        embed_dim: 1024
        depth: 8
        decoder_depth: 2
        num_heads: 16
        mlp_ratio: 4
        drop_path: 0.1
        drop_rate: 0.1

# ---------------------------- DATA -------------------------------------------
data:
  # Parameters for WildfireDataModule
  root_dir: /media/staging1/dhwang/climate_npz/compressed  # Directory containing NPZ files
  
  # Variables for input 
  variables: [
    "I1", "M4", "M3", "M11", "I2", "I3", "aerosol depth", "NDVI_last", "EVI2_last",
    "total precipitation", "wind speed", "wind direction", "minimum temperature",
    "maximum temperature", "energy release component", "specific humidity",
    "pdsi", "LC_Type1", "forecast total precipitation", "forecast wind speed",
    "forecast wind direction", "forecast temperature", "forecast specific humidity",
    "slope", "aspect", "elevation"
  ]
  
  # Date filtering
  valid_dates_csv: /media/staging1/dhwang/climate_npz/compressed/complete_channels.csv # Path to CSV file with valid dates, leave empty to use all dates
  
  # Data split parameters
  train_ratio: 1.0
  val_ratio: 0.0
  test_ratio: 0.0
  
  # Forecast parameters
  prediction_range: 7   # Max days ahead for target data
  min_prediction_range: 1 # Min days ahead for target data
  random_lead_time: false  # Sample lead time randomly in [min, max] range during training

  # Data processing parameters
  patch_size: [128, 128]  # Target height/width for each data patch
  
  # Shuffle buffer size (new parameter for streaming datasets)
  buffer_size: 10000  # Size of buffer for shuffling samples in streaming datasets

  # DataLoader parameters
  batch_size: 128
  num_workers: 1
  pin_memory: False
  
  # Excluded variables (optional)
  # excluded_vars: [
  #   "specific humidity",
  #   "wind direction", 
  #   "wind speed",
  #   "elevation",
  #   "M11",
  #   "I2",
  #   "I1",
  #   "pdsi"
  # ]